name: Pull Request CI

on:
  pull_request:

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php-version: [7.2, 7.3, 7.4]

    steps:
      - name: Echo environment
        run: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Setup dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-suggest --ignore-platform-reqs

      - name: "Run phpunit"
        run: composer phpunit

      - name: "Run phpstan"
        run: composer phpstan

      - name: "Run php_codesniffer"
        run: composer phpcs
